### ISSUE TITLE
Netbeans plugin dialog became unusable

### ISSUE THREAD

**Issue by pine3ree** [junichi11/netbeans-color-codes-preview#37]
After installing the plugin the app plugin window is unusable, no plugin is visible in any list. Removing (manually) the plugin from the user directory restores the correct behaviour in netbeans.

Apache netbeans 11.0 and 11.2
Java Oracle 9.0.4
Linux MInt (ubuntu 16.04 LTS xenial based)

Steps to reproduce:
- Install the plugin
- Reopen the menu item Tools>Plugins => any tab show zero elements in the plugin list. Only the Settings tab is working.

kind regards,
maks

**Comment by junichi11** [comment]
Unfortunately, I can't reproduce it.

![nb-color-codes-preview-37](https://user-images.githubusercontent.com/738383/73316719-31119a00-4277-11ea-9c3c-0103c29e7156.png)
![nb-color-codes-preview-37-2](https://user-images.githubusercontent.com/738383/73316721-3373f400-4277-11ea-8bcb-a2f8a34821d7.png)

Please attach a screenshot if possible.

#### My environments

Product Version: Apache NetBeans IDE 11.0 (Build incubator-netbeans-release-404-on-20190319)
Java: 1.8.0_202; Java HotSpot(TM) 64-Bit Server VM 25.202-b08
Runtime: Java(TM) SE Runtime Environment 1.8.0_202-b08
System: Linux version 4.16.0-041600-generic running on amd64; UTF-8;

**Comment by pine3ree** [comment]
Hello @junichi11,
here a couple of screenshots, during installation and after,

![netbeans-11-0--20200129-041044](https://user-images.githubusercontent.com/3229979/73325425-c482a500-424e-11ea-8a64-007cbb1499a6.png)
![netbeans-11-0--20200129-041544](https://user-images.githubusercontent.com/3229979/73325427-c8162c00-424e-11ea-96b0-49da60f2e6c8.png)

I found a ArrayIndexOutOfBoundException. The followind is part of the IDE log:

```
>System Info: 
  Product Version         = Apache NetBeans IDE 11.0 (Build incubator-netbeans-release-404-on-20190319)
  Operating System        = Linux version 4.4.0-67-generic running on amd64
  Java; VM; Vendor        = 9.0.4; Java HotSpot(TM) 64-Bit Server VM 9.0.4+11; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 9.0.4+11
  Java Home               = /usr/lib/jvm/java-9-oracle
```
```
INFO [org.netbeans.core.startup.ModuleList]
java.lang.ArrayIndexOutOfBoundsException: 64
	at java.base/java.util.jar.JarFile.match(JarFile.java:941)
	at java.base/java.util.jar.JarFile.checkForSpecialAttributes(JarFile.java:971)
	at java.base/java.util.jar.JarFile.isMultiRelease(JarFile.java:366)
	at java.base/java.util.jar.JarFile$JarFileEntry.<init>(JarFile.java:604)
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:487)
	at org.netbeans.JarClassLoader$JarSource.resource(JarClassLoader.java:599)
	at org.netbeans.Archive.getData(Archive.java:187)
	at org.netbeans.JarClassLoader$JarSource.readClass(JarClassLoader.java:576)
	at org.netbeans.JarClassLoader$Source.getClassData(JarClassLoader.java:371)
	at org.netbeans.JarClassLoader.doLoadClass(JarClassLoader.java:213)
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:234)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:162)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.netbeans.core.startup.NbInstaller.prepare(NbInstaller.java:173)
Caused: org.netbeans.InvalidException: StandardModule:com.junichi11.netbeans.modules.color.codes.preview jarFile: /root/.netbeans/11.0/modules/com-junichi11-netbeans-modules-color-codes-preview.jar
```

I have also your Extended PHP plugin installed, but it does not cause any issue.

thank you and kind regards,
maks

**Comment by pine3ree** [comment]
PS.
I removed manually every plugin in my user dir, even if the color-codes-preview is the only plugin present i get the same issue.

**Comment by junichi11** [comment]
Umm, As I wrote above, I can't reproduce it. So, I'm not sure about the cause.
Please try using another Java version.

**Comment by pine3ree** [comment]
Thank You @junichi11, 
I installed _java-1.8.0-openjdk-amd64_ and it works fine with that version.
Maybe it's better to use openjdk "now" that netbeans is an apache project and Oracle's  no more... :-)
kind regards!
